import java.util.ArrayDeque;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.Map;

public final class CodeGenerator {
    private final String className;
    private final StringBuilder out = new StringBuilder();
    private final Deque<Map<String, String>> scopes = new ArrayDeque<>();
    private int indent = 0;
    private int nextVariableId = 0;

    public CodeGenerator(String className) {
        this.className = className;
    }

    public String generate(Ast.Program program) {
        out.setLength(0);
        scopes.clear();
        indent = 0;
        nextVariableId = 0;

        line("// Auto-generated by the Bangla Programming Language Compiler.");
        line("// Do not edit this file manually; edit the .bng source instead.");
        line("public class " + className + " {");
        indent++;
        emitRuntimeHelpers();
        line("");
        line("public static void main(String[] args) {");
        indent++;
        beginScope();
        for (Ast.Stmt stmt : program.statements) emitStmt(stmt);
        endScope();
        indent--;
        line("}");
        indent--;
        line("}");

        return out.toString();
    }

    private void emitStmt(Ast.Stmt stmt) {
        if (stmt instanceof Ast.VarDecl s) {
            String initializer = emitExpr(s.initializer); // resolve outer scope before shadowing
            String javaName = declare(s.name.lexeme);
            line(s.declaredType.javaName() + " " + javaName + " = " + initializer + ";");
        } else if (stmt instanceof Ast.Assign s) {
            line(resolve(s.name.lexeme) + " = " + emitExpr(s.value) + ";");
        } else if (stmt instanceof Ast.Print s) {
            line("System.out.println(" + emitExpr(s.expression) + ");");
        } else if (stmt instanceof Ast.If s) {
            line("if (" + emitExpr(s.condition) + ") {");
            indent++;
            emitBlockContents(s.thenBranch);
            indent--;
            if (s.elseBranch != null) {
                line("} else {");
                indent++;
                emitBlockContents(s.elseBranch);
                indent--;
            }
            line("}");
        } else if (stmt instanceof Ast.While s) {
            line("while (" + emitExpr(s.condition) + ") {");
            indent++;
            emitBlockContents(s.body);
            indent--;
            line("}");
        } else if (stmt instanceof Ast.Block s) {
            line("{");
            indent++;
            emitBlockContents(s);
            indent--;
            line("}");
        }
    }

    private void emitBlockContents(Ast.Block block) {
        beginScope();
        for (Ast.Stmt stmt : block.statements) emitStmt(stmt);
        endScope();
    }

    private String emitExpr(Ast.Expr expr) {
        if (expr instanceof Ast.Literal e) return e.javaText;
        if (expr instanceof Ast.Variable e) return resolve(e.name.lexeme);
        if (expr instanceof Ast.Grouping e) return "(" + emitExpr(e.expression) + ")";
        if (expr instanceof Ast.Unary e) return "(" + e.operator.lexeme + emitExpr(e.right) + ")";
        if (expr instanceof Ast.Binary e) {
            String left = emitExpr(e.left);
            String right = emitExpr(e.right);
            if (e.operator.type == TokenType.SLASH) {
                return "_bng_div(" + left + ", " + right + ")";
            }
            if (e.operator.type == TokenType.PERCENT) {
                return "_bng_mod(" + left + ", " + right + ")";
            }
            return "(" + left + " " + e.operator.lexeme + " " + right + ")";
        }
        throw new IllegalStateException("Unknown expression node in code generator.");
    }

    private void emitRuntimeHelpers() {
        line("private static int _bng_div(int left, int right) {");
        indent++;
        line("if (right == 0) {");
        indent++;
        line("System.err.println(\"RUNTIME ERROR: Division by zero.\");");
        line("System.exit(1);");
        line("return 0;");
        indent--;
        line("}");
        line("return left / right;");
        indent--;
        line("}");
        line("");

        line("private static double _bng_div(double left, double right) {");
        indent++;
        line("if (right == 0.0) {");
        indent++;
        line("System.err.println(\"RUNTIME ERROR: Division by zero.\");");
        line("System.exit(1);");
        line("return 0.0;");
        indent--;
        line("}");
        line("return left / right;");
        indent--;
        line("}");
        line("");

        line("private static int _bng_mod(int left, int right) {");
        indent++;
        line("if (right == 0) {");
        indent++;
        line("System.err.println(\"RUNTIME ERROR: Remainder by zero.\");");
        line("System.exit(1);");
        line("return 0;");
        indent--;
        line("}");
        line("return left % right;");
        indent--;
        line("}");
        line("");

        line("private static double _bng_mod(double left, double right) {");
        indent++;
        line("if (right == 0.0) {");
        indent++;
        line("System.err.println(\"RUNTIME ERROR: Remainder by zero.\");");
        line("System.exit(1);");
        line("return 0.0;");
        indent--;
        line("}");
        line("return left % right;");
        indent--;
        line("}");
    }

    private String declare(String sourceName) {
        String javaName = "_bng_" + (nextVariableId++);
        scopes.peek().put(sourceName, javaName);
        return javaName;
    }

    private String resolve(String sourceName) {
        for (Map<String, String> scope : scopes) {
            String javaName = scope.get(sourceName);
            if (javaName != null) return javaName;
        }
        // Semantic analysis runs first; reaching this point indicates an internal bug.
        throw new IllegalStateException("Unresolved variable during code generation: " + sourceName);
    }

    private void beginScope() {
        scopes.push(new LinkedHashMap<>());
    }

    private void endScope() {
        scopes.pop();
    }

    private void line(String text) {
        out.append("    ".repeat(Math.max(0, indent))).append(text).append(System.lineSeparator());
    }
}
